name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig fmt --check src test/tls_interop_server.zig build.zig
      - run: zig build test --test-timeout 60s
      - run: zig build fuzz --fuzz=100K
      - run: zig build interop

  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-linux
          - aarch64-linux
          - x86_64-macos
          - aarch64-macos
          - x86_64-windows
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
          cache-key: ${{ matrix.target }}
      - run: zig build -Dtarget=${{ matrix.target }}
